service:
  port: 80
  targetPort: 8080

imageRepository: "669171879954.dkr.ecr.us-east-1.amazonaws.com/otp-service"
imageTag: "211faf5"
imagepullPolicy: Always
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 500M

readinessProbe:
  initialDelaySeconds: 120

livenessProbe:
  initialDelaySeconds: 120

configMap:
  spring.profiles.active: dev
  SERVER_PORT: "8080"
  MONGODB_Host: mongodb://mongo-mongodb-headless:27017/luthersales
  OTP_EXPIRY_TIME: 10
  NOTIFICATION_EUREKA_URL: http://NOTIFICATION-SERVICE
  NOTIFICATION_SMS_URL: /api/v1/notifications/sms
  NOTIFICATION_EMAIL_SERVICE: /api/v1/notifications/email
