
{{- if .Release.IsInstall -}}
{{- $runInit := true -}}
{{- if (hasKey .Values.migrations "init") -}}
  {{- $runInit = .Values.migrations.init -}}
{{- end -}}

{{- if (and ($runInit) (not (eq .Values.configMap.KONG_DATABASE "off"))) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "serviceId.name" . }}-init-migrations
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: {{ template "serviceId.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    namespace: "{{ .Release.Namespace }}"
    app.kubernetes.io/component: init-migrations
spec:
  template:
    metadata:
      name: {{ template "serviceId.name" . }}-init-migrations
      labels:
        app: {{ template "serviceId.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        namespace: "{{ .Release.Namespace }}"
        app.kubernetes.io/component: init-migrations
    spec:
      containers:
      - name: {{ template "serviceId.name" . }}-migrations
        image: "{{ .Values.imageRepository }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagepullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ template "serviceId.name" . }}
        env:      
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "serviceId.name" . }}
              key: kong-password      
        args: [ "kong", "migrations", "bootstrap" ]
        volumeMounts:
          - name: {{ template "serviceId.name" . }}-prefix-dir
            mountPath: /kong_prefix/
          - name: {{ template "serviceId.name" . }}-tmp
            mountPath: /tmp
        resources: 
        {{- toYaml .Values.resources | nindent 10 }}
      restartPolicy: OnFailure
      volumes:
        - name: {{ template "serviceId.name" . }}-prefix-dir
          emptyDir: {}
        - name: {{ template "serviceId.name" . }}-tmp
          emptyDir: {}
{{- end }}
{{- end }}

