# Global Docker Registry Settings
image:
  registry:
  pullPolicy: Always


dbType: mssql

debug:
  enabled: false
  port: 5005

readinessProbe:
  initialDelaySeconds: 120

livenessProbe:
  initialDelaySeconds: 120

build:
  number: 0

imageRepository: "669171879954.dkr.ecr.us-east-1.amazonaws.com/helper-service"
imageTag: "1.0"
imagepullPolicy: Always
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 1Gi

service:
  port: 8080
  targetPort: 8080

configMap:
  spring.profiles.active: dev
  SERVER_PORT: "8080"
  APPLICATION_NAME: helper-service
  DEFAULT_URL: http://eureka-server:8761/eureka
