service:
  port: 80
  targetPort: 30013
  
imageRepository: "669171879954.dkr.ecr.us-east-1.amazonaws.com/pw-client-test-app"
imageTag: "afe6de4"
imagepullPolicy: Always
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 500M

readinessProbe:
  initialDelaySeconds: 120

livenessProbe:
  initialDelaySeconds: 120

configMap:
