# Global Docker Registry Settings
image:
  registry:
  pullPolicy: Always
# Optionally specify an array of imagePullSecrets.
# Secrets must be manually created in the namespace.
# ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
imagePullSecrets:
  - name: acr-auth

dbType: mssql

debug:
  enabled: false
  port: 5005

readinessProbe:
  initialDelaySeconds: 120

livenessProbe:
  initialDelaySeconds: 120

build:
  number: 0

imageRepository: "669171879954.dkr.ecr.us-east-1.amazonaws.com/notification-service "
imageTag: "1.0"
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 1Gi

service:
  port: 8080
  targetPort: 8080
