apiVersion: v1
kind: Service
metadata:
  name: luther-sales-borrower-app
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "aws-load-balancer-controller.labels" . | indent 4 }}
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 4 }}
