apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "serviceId.name" . }}
  labels:
    app: {{ template "serviceId.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "serviceId.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "serviceId.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        namespace: "{{ .Release.Namespace }}"
    spec:
      containers:
        - name: {{ template "serviceId.name" . }}
          image: "{{ .Values.imageRepository }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagepullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
          - name: https
            containerPort: 8443
            protocol: TCP
          - name: http
            containerPort: 8080
            protocol: TCP
          volumeMounts:
            - name: {{ template "serviceId.name" . }}-prefix-dir
              mountPath: /keycloak_prefix/
            - name: {{ template "serviceId.name" . }}-tmp
              mountPath: /tmp  
          envFrom:
            - configMapRef:
                name: {{ template "serviceId.name" . }}
          env:      
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "serviceId.name" . }}
                  key: {{ template "serviceId.name" . }}-password      

          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}    
      volumes:
        - name: {{ template "serviceId.name" . }}-prefix-dir
          emptyDir: {}
        - name: {{ template "serviceId.name" . }}-tmp
          emptyDir: {}



