service:
  port: 80
  targetPort: 3000
  
imageRepository: "669171879954.dkr.ecr.us-east-1.amazonaws.com/pwc-app-ui"
imageTag: "1.0"
imagepullPolicy: Always
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 500M

readinessProbe:
  initialDelaySeconds: 120

livenessProbe:
  initialDelaySeconds: 120

configMap:
