# Global Docker Registry Settings
image:
  registry:
  pullPolicy: Always


dbType: mssql

debug:
  enabled: false
  port: 5005

readinessProbe:
  initialDelaySeconds: 120

livenessProbe:
  initialDelaySeconds: 120

build:
  number: 0

imageRepository: "669171879954.dkr.ecr.us-east-1.amazonaws.com/verification-link-service"
imageTag: "1.0"
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 500M

service:
  port: 8080
  targetPort: 8080

configMap:
  spring.profiles.active: dev
  SERVER_PORT: "8080"
  MONGODB_Host: mongodb://mongo-mongodb-headless:27017/luthersales
  LINK_EXPIRYTIME: 4320
  OTP_EUREKA_URI: http://OTP-SERVICE
  APPLICATION_NAME: verification-link-service
  EUREKA_CLIENT_SERVICEURL: http://eureka-server:8761/eureka
