{{- if .Values.secret.enabled }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
  labels:
spec:
  backendType: systemManager
  {{- with .Values.secrets }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
