service:
  port: 80
  targetPort: 8080
  
imageRepository: "669171879954.dkr.ecr.us-east-1.amazonaws.com/new-payroll-provider-service"
imageTag: "1.1"
imagepullPolicy: Always
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 500M

readinessProbe:
  initialDelaySeconds: 120

livenessProbe:
  initialDelaySeconds: 120

  configMap:
    spring.profiles.active: dev
    SERVER_PORT: "8080"
    MONGODB_Host: mongodb://mongo-mongodb-headless:27017/luthersales
    ARGYLE_BASE_LINK: https://api-sandbox.argyle.io/link/v1/
    SERVICE_ID: Salary Allocation
    NEW_PAYROLL_SERVICE: http://NEW-PAYROLL-PROVIDER-SERVICE/api/v1
    ATOMICFI_ACCOUNT_NUMBER: 30909999
    ATOMICFI_ROUNTING_NUMBER: 121000248
    ATOMICFI_ACCOUNTS_TYPE: checking
    ATOMICFI_ACCOUNTS_TITLE: Premier Plus Checking
    ATOMICFI_BASE: https://sandbox-api.atomicfi.com/
    ATOMICFI_API_KEY: 626fb572-b945-4ea1-81a9-b2d8bc7ebac2
    ATOMICFI_SECRET: eb28fd6b-fa28-40f3-aed1-6d52f4916065
    ATOMICFI_TOKEN_VALIDITY_HRS: 24
    APPLICATION_NAME: payroll-provider
    DEFAULT_URL: http://eureka-server:8761/eureka
