apiVersion: v1
kind: Secret
metadata:
  name: {{ template "serviceId.name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
data:
  username: fineract
  password: payufineract 
