service:
  port: 80
  targetPort: 1337

imageRepository: pantsel/konga
imageTag: latest
imagepullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 300m
    memory: 256Mi

#readinessProbe for Kong pods
readinessProbe:
 httpGet:
   path: /register
   port: http
 initialDelaySeconds: 60
 timeoutSeconds: 5
 periodSeconds: 10
 successThreshold: 1
 failureThreshold: 3

#livenessProbe for Kong pods
livenessProbe:
 httpGet:
   path: /register
   port: http
 initialDelaySeconds: 60
 timeoutSeconds: 5
 periodSeconds: 10
 successThreshold: 1
 failureThreshold: 3

terminationGracePeriodSeconds: 30

configMap:
   port: "1337"
   KONGA_ENV: "development"
   konga_hook_timeout: "60"
   DB_ADAPTER: postgres
   DB_HOST: uat-kong-konga-keycloak.cluster-ckluizvytk2n.us-east-1.rds.amazonaws.com
   DB_PORT: "5432"
   DB_USER: "kong"
   DB_DATABASE: "kong"
   DB_PASSWORD: "payukong"
   log_level: "debug"
