service:
  port: 80
  targetPort: 8080

imageRepository: pantsel/konga
imageTag: latest
imagepullPolicy: Always

resources: {}
# readinessProbe for Kong pods
#readinessProbe:
#  httpGet:
#    path: /
#    port: http
#  initialDelaySeconds: 300
#  timeoutSeconds: 5
#  periodSeconds: 10
#  successThreshold: 1
#  failureThreshold: 3

# livenessProbe for Kong pods
#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#  initialDelaySeconds: 300
#  timeoutSeconds: 5
#  periodSeconds: 10
#  successThreshold: 1
#  failureThreshold: 3

terminationGracePeriodSeconds: 30

secert:
  kong: payukong

configMap:
   port: "1337"
   #node_env: "development"
   KONGA_ENV: "development"
   konga_hook_timeout: "60"
   DB_ADAPTER: postgres
   DB_HOST: dev-kong-konga.cluster-ckluizvytk2n.us-east-1.rds.amazonaws.com
   DB_PORT: "5432"
   DB_USER: "kong"
   DB_PASSWORD: "payukong"
   DB_DATABASE: "kong"
   log_level: "debug"
