kind: Service
apiVersion: v1
metadata:
  name: {{ template "serviceId.name" . }}
  labels:
    app: {{ template "serviceId.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    namespace: "{{ .Release.Namespace }}"
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
  selector:
    app: {{ template "serviceId.name" . }}
    release: "{{ .Release.Name }}"
