# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: 669171879954.dkr.ecr.us-east-1.amazonaws.com/eureka-service
  tag: 1.1
  pullPolicy: Always

service:
  name: eureka-server
  type: ClusterIP
  port: 8761
  internalPort: 8761

config:
  existingConfigMapName:

spring:
  cloud:
    config:
      enabled: false
      uri: 

global:
  useConfigServerBootstrap: false
