container:
  arg: ["-Dspring.profiles.active=dev"]
  env:
    JAVA_OPTIONS: ""

service:
  port: 80
  targetPort: 8080

imageRepository: "669171879954.dkr.ecr.us-east-1.amazonaws.com/pw-underwriting-service"
imageTag: "1.0"
imagepullPolicy: Always
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 500M

readinessProbe:
  initialDelaySeconds: 120

livenessProbe:
  initialDelaySeconds: 120

configMap:
  spring.profiles.active: dev

secret:
  enabled: false

secretName: underwriting

secrets:
  - key: /underwriting-test-value1
    name: test_value1
  - key: /underwriting-test-value2
    name: test_value2


